name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install tools
      run: sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
      
    #- name: Set Up Env
    #  run: export DISPLAY=:0.0

    - name: Build
      run: go build Main.go

    - name: Test
      run: make test
